[project]
name = "bonsai-reactiontimetask-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "harp-python>=0.4.1",
    "jupyterlab>=4.4.10",
    "matplotlib>=3.10.7",
]
